services:
  backend:
    container_name: ihys_backend
    build:
      context: ./backend
      # Use DOCKER_TARGET env var to switch between 'dev' and 'prod' stages
      # Defaults to 'dev' if not set
      target: ${DOCKER_TARGET:-dev}
    restart: unless-stopped
    ports:
      - "8002:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./.env.backend

  frontend:
    container_name: ihys_frontend
    build:
      context: ./frontend
      target: ${DOCKER_TARGET:-dev}
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.nuxt
    env_file:
      - ./.env.frontend
    environment:
      - NUXT_HOST=0.0.0.0
    depends_on:
      - backend
