create table if not exists public.users (
    id bigint generated by default as identity primary key,
    mal_id text not null unique,
    mal_username text not null,
    encrypted_access_token text not null,
    encrypted_refresh_token text not null,
    token_expires_at timestamptz not null,
    auth_user_id uuid,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.anime (
    id bigint generated by default as identity primary key,
    name text not null unique,
    english_title text,
    japanese_title text,
    episodes text,
    status text,
    aired text,
    source text,
    genres text,
    themes text,
    duration text,
    rating text,
    score text,
    ranked text,
    popularity text,
    synopsis text,
    mal_id integer unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.actors (
    id bigint generated by default as identity primary key,
    name text not null unique,
    photo text not null default '',
    created_at timestamptz not null default now()
);

create table if not exists public.characters (
    id bigint generated by default as identity primary key,
    name text not null,
    photo text not null default '',
    anime_id bigint not null references public.anime(id) on delete cascade,
    created_at timestamptz not null default now(),
    unique (name, anime_id)
);

create table if not exists public.character_actors (
    id bigint generated by default as identity primary key,
    character_id bigint not null references public.characters(id) on delete cascade,
    actor_id bigint not null references public.actors(id) on delete cascade,
    unique (character_id, actor_id)
);

create table if not exists public.user_anime (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    anime_id bigint not null references public.anime(id) on delete cascade,
    mal_anime_id integer,
    watch_status text not null default 'completed',
    score integer,
    episodes_watched integer,
    start_date date,
    finish_date date,
    is_synced_from_mal boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, anime_id)
);

create index if not exists anime_mal_id_idx on public.anime(mal_id);
create index if not exists characters_anime_id_idx on public.characters(anime_id);
create index if not exists character_actors_character_id_idx
    on public.character_actors(character_id);
create index if not exists character_actors_actor_id_idx
    on public.character_actors(actor_id);
create index if not exists user_anime_user_id_idx on public.user_anime(user_id);
create index if not exists user_anime_anime_id_idx on public.user_anime(anime_id);
